language: go

go:
  - 1.15.x

env:
  - GO111MODULE=on

addons:
  apt_packages:
    - socat

notifications:
  email: false

git:
  depth: 1

install:
  - make install

script:
  - make test

# after_success:
#   - make coverage
